name: esafe
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - geopandas
  - shapely
  - fiona
  - pyproj
  - rtree
  - rasterio
  - scipy
  - streamlit
  - openpyxl
  - openjdk=11
  - maven
  - pip
