# Oracle profile
risk.db.driver=oracle.jdbc.OracleDriver
risk.db.url=jdbc:oracle:thin:@localhost:1521/ORCL
risk.db.username=RISK_USER
risk.db.password=RISK_PASS
risk.db.initialSize=5
risk.db.maxTotal=20
risk.db.maxIdle=10
risk.db.minIdle=5
risk.db.validationQuery=SELECT 1 FROM DUAL
risk.db.testOnBorrow=true
risk.db.init.enabled=false
risk.weather.alert.zone.file=
risk.map.vworld.apiKey=60099EA2-ECE4-3BA3-9585-5A829AACC420
