# H2 local profile
risk.db.driver=org.h2.Driver
risk.db.url=jdbc:h2:mem:riskdb;MODE=Oracle;DB_CLOSE_DELAY=-1
risk.db.username=sa
risk.db.password=
risk.db.initialSize=1
risk.db.maxTotal=10
risk.db.maxIdle=5
risk.db.minIdle=1
risk.db.validationQuery=SELECT 1
risk.db.testOnBorrow=true
risk.db.init.enabled=true
risk.weather.alert.zone.file=
risk.map.vworld.apiKey=60099EA2-ECE4-3BA3-9585-5A829AACC420
