-- H2 local branch-to-HQ mapping table.
-- 전국 사업소 일람표 기준(로컬 테스트용)

CREATE TABLE IF NOT EXISTS TB_BRANCH_HQ_MAP (
    BRANCH_NM VARCHAR(100) PRIMARY KEY,
    HQ_NM     VARCHAR(100) NOT NULL,
    USE_YN    CHAR(1) DEFAULT 'Y',
    REG_DT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('서울본부', '서울본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('서울본부직할', '서울본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('서울동부지사', '서울본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('서울서부지사', '서울본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('서울남부지사', '서울본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('서울북부지사', '서울본부', 'Y');

MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('부산울산본부', '부산울산본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('부산울산본부직할', '부산울산본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('울산지사', '부산울산본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('부산동부지사', '부산울산본부', 'Y');

MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('대구경북본부', '대구경북본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('대구경북본부직할', '대구경북본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('대구서부지사', '대구경북본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('구미칠곡지사', '대구경북본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('경북동부지사', '대구경북본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('경북서부지사', '대구경북본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('경북북부지사', '대구경북본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('경주지사', '대구경북본부', 'Y');

MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('인천본부', '인천본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('인천본부직할', '인천본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('인천서부지사', '인천본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('부천김포지사', '인천본부', 'Y');

MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('광주전남본부', '광주전남본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('광주전남본부직할', '광주전남본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('전남동부지사', '광주전남본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('전남서부지사', '광주전남본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('전남남부지사', '광주전남본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('여수지사', '광주전남본부', 'Y');

MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('대전세종충남본부', '대전세종충남본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('대전세종충남본부직할', '대전세종충남본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('천안아산지사', '대전세종충남본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('충남중부지사', '대전세종충남본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('충남남부지사', '대전세종충남본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('서산태안지사', '대전세종충남본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('충남서부지사', '대전세종충남본부', 'Y');

MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('경기본부', '경기본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('경기본부직할', '경기본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('경기중부지사', '경기본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('안산시흥지사', '경기본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('경기서부지사', '경기본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('평택안성지사', '경기본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('이천여주지사', '경기본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('용인지사', '경기본부', 'Y');

MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('경기북부본부', '경기북부본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('경기북부본부직할', '경기북부본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('고양파주지사', '경기북부본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('경기북동부지사', '경기북부본부', 'Y');

MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('강원본부', '강원본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('강원본부직할', '강원본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('강원동부지사', '강원본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('원주횡성지사', '강원본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('강원북부지사', '강원본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('강원남부지사', '강원본부', 'Y');

MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('충북본부', '충북본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('충북본부직할', '충북본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('충주음성지사', '충북본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('제천단양지사', '충북본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('영동옥천지사', '충북본부', 'Y');

MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('전북본부', '전북본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('전북본부직할', '전북본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('전북서부지사', '전북본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('익산지사', '전북본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('군산지사', '전북본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('남원순창지사', '전북본부', 'Y');

MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('경남본부', '경남본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('경남본부직할', '경남본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('김해양산지사', '경남본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('경남서부지사', '경남본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('경남남부지사', '경남본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('경남북부지사', '경남본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('밀양창녕지사', '경남본부', 'Y');

MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('제주본부', '제주본부', 'Y');
MERGE INTO TB_BRANCH_HQ_MAP (BRANCH_NM, HQ_NM, USE_YN) KEY(BRANCH_NM) VALUES ('제주본부직할', '제주본부', 'Y');
