--------------------------------------------------------------------------------
-- Branch -> HQ mapping table (Oracle 19c)
-- 전국 사업소 일람표 기준
--------------------------------------------------------------------------------

CREATE TABLE TB_BRANCH_HQ_MAP (
    BRANCH_NM   VARCHAR2(100)   NOT NULL,
    HQ_NM       VARCHAR2(100)   NOT NULL,
    USE_YN      CHAR(1)         DEFAULT 'Y' NOT NULL,
    REG_DT      TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_BRANCH_HQ_MAP PRIMARY KEY (BRANCH_NM)
);

COMMENT ON TABLE TB_BRANCH_HQ_MAP IS '지사/사업소명 -> 본부명 매핑';
COMMENT ON COLUMN TB_BRANCH_HQ_MAP.BRANCH_NM IS '지사/사업소명';
COMMENT ON COLUMN TB_BRANCH_HQ_MAP.HQ_NM IS '본부명';
COMMENT ON COLUMN TB_BRANCH_HQ_MAP.USE_YN IS '사용여부(Y/N)';

-- 서울본부
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '서울본부' BRANCH_NM, '서울본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '서울본부직할' BRANCH_NM, '서울본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '서울동부지사' BRANCH_NM, '서울본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '서울서부지사' BRANCH_NM, '서울본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '서울남부지사' BRANCH_NM, '서울본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '서울북부지사' BRANCH_NM, '서울본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');

-- 부산울산본부
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '부산울산본부' BRANCH_NM, '부산울산본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '부산울산본부직할' BRANCH_NM, '부산울산본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '울산지사' BRANCH_NM, '부산울산본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '부산동부지사' BRANCH_NM, '부산울산본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');

-- 대구경북본부
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '대구경북본부' BRANCH_NM, '대구경북본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '대구경북본부직할' BRANCH_NM, '대구경북본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '대구서부지사' BRANCH_NM, '대구경북본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '구미칠곡지사' BRANCH_NM, '대구경북본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '경북동부지사' BRANCH_NM, '대구경북본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '경북서부지사' BRANCH_NM, '대구경북본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '경북북부지사' BRANCH_NM, '대구경북본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '경주지사' BRANCH_NM, '대구경북본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');

-- 인천본부
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '인천본부' BRANCH_NM, '인천본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '인천본부직할' BRANCH_NM, '인천본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '인천서부지사' BRANCH_NM, '인천본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '부천김포지사' BRANCH_NM, '인천본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');

-- 광주전남본부
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '광주전남본부' BRANCH_NM, '광주전남본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '광주전남본부직할' BRANCH_NM, '광주전남본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '전남동부지사' BRANCH_NM, '광주전남본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '전남서부지사' BRANCH_NM, '광주전남본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '전남남부지사' BRANCH_NM, '광주전남본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '여수지사' BRANCH_NM, '광주전남본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');

-- 대전세종충남본부
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '대전세종충남본부' BRANCH_NM, '대전세종충남본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '대전세종충남본부직할' BRANCH_NM, '대전세종충남본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '천안아산지사' BRANCH_NM, '대전세종충남본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '충남중부지사' BRANCH_NM, '대전세종충남본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '충남남부지사' BRANCH_NM, '대전세종충남본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '서산태안지사' BRANCH_NM, '대전세종충남본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '충남서부지사' BRANCH_NM, '대전세종충남본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');

-- 경기본부
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '경기본부' BRANCH_NM, '경기본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '경기본부직할' BRANCH_NM, '경기본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '경기중부지사' BRANCH_NM, '경기본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '안산시흥지사' BRANCH_NM, '경기본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '경기서부지사' BRANCH_NM, '경기본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '평택안성지사' BRANCH_NM, '경기본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '이천여주지사' BRANCH_NM, '경기본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '용인지사' BRANCH_NM, '경기본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');

-- 경기북부본부
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '경기북부본부' BRANCH_NM, '경기북부본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '경기북부본부직할' BRANCH_NM, '경기북부본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '고양파주지사' BRANCH_NM, '경기북부본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '경기북동부지사' BRANCH_NM, '경기북부본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');

-- 강원본부
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '강원본부' BRANCH_NM, '강원본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '강원본부직할' BRANCH_NM, '강원본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '강원동부지사' BRANCH_NM, '강원본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '원주횡성지사' BRANCH_NM, '강원본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '강원북부지사' BRANCH_NM, '강원본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '강원남부지사' BRANCH_NM, '강원본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');

-- 충북본부
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '충북본부' BRANCH_NM, '충북본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '충북본부직할' BRANCH_NM, '충북본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '충주음성지사' BRANCH_NM, '충북본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '제천단양지사' BRANCH_NM, '충북본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '영동옥천지사' BRANCH_NM, '충북본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');

-- 전북본부
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '전북본부' BRANCH_NM, '전북본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '전북본부직할' BRANCH_NM, '전북본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '전북서부지사' BRANCH_NM, '전북본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '익산지사' BRANCH_NM, '전북본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '군산지사' BRANCH_NM, '전북본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '남원순창지사' BRANCH_NM, '전북본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');

-- 경남본부
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '경남본부' BRANCH_NM, '경남본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '경남본부직할' BRANCH_NM, '경남본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '김해양산지사' BRANCH_NM, '경남본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '경남서부지사' BRANCH_NM, '경남본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '경남남부지사' BRANCH_NM, '경남본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '경남북부지사' BRANCH_NM, '경남본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '밀양창녕지사' BRANCH_NM, '경남본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');

-- 제주본부
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '제주본부' BRANCH_NM, '제주본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');
MERGE INTO TB_BRANCH_HQ_MAP t USING (SELECT '제주본부직할' BRANCH_NM, '제주본부' HQ_NM FROM dual) s
ON (t.BRANCH_NM = s.BRANCH_NM)
WHEN MATCHED THEN UPDATE SET t.HQ_NM = s.HQ_NM, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (BRANCH_NM, HQ_NM, USE_YN) VALUES (s.BRANCH_NM, s.HQ_NM, 'Y');

COMMIT;